name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]

    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      if: startsWith(matrix.os,'windows')

    - name: Add Windows SDK
      shell: cmd
      if: startsWith(matrix.os,'windows')
      run: |
        choco install windows-sdk-8.1

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.9'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.1
      with:
        output-dir: wheelhouse
      env:
        CIBW_BUILD: cp38-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"
        CIBW_TEST_REQUIRES: pytest
        CIBW_TEST_COMMAND: "pytest -s {project}/src/osqp/tests"

    - name: Build source
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        python -m build . --sdist --outdir wheelhouse

    - name: Release to pypi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python -m pip install --upgrade twine
        twine upload wheelhouse/*

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse

  build_aarch64_wheels:
    name: Build wheel on aarch64
    runs-on: ubuntu-18.04
    strategy:
      matrix:
       python_tag: ["cp37-*", "cp38-*", "cp39-*"]
    env:
      CIBW_ARCHS_LINUX: aarch64
      CIBW_BUILD: ${{matrix.python_tag}}
      _CIBW_BEFORE_ALL: "yum -y update && yum install -y blas-devel lapack-devel suitesparse-devel"
      CIBW_TEST_COMMAND: "pytest -s {project}/module/tests"

    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v1
      name: Install Python 3.9
      with:
        python-version: "3.9"

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.10.0

    - uses: docker/setup-qemu-action@v1
      name: Set up QEMU

    - name: Build wheels
      run: |
         python -m cibuildwheel --output-dir wheelhouse
    - name: Release to pypi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python -m pip install --upgrade twine
        twine upload wheelhouse/*
    - name: Upload artifacts to github
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
